site_name: Tevico Community
theme:
  name: material
  font:
    text: Hanken Grotesk
    code: Roboto Mono
  logo: assets/logo.png
  favicon: assets/logo.png
  features:
    - navigation.instant
    - navigation.instant.progress
    - navigation.sections
    - navigation.top
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.expand
    - navigation.path
    - search.suggest
    - search.highlight
    - content.tabs.link
    - content.code.copy
    - toc.follow
  
  # At a later time, we can define the light and the dark theme for the website
  palette:
    scheme: default
    primary: white
    accent: indigo

nav:
  - Get Started:
    - Welcome to Tevico Community: index.md
    - Manually Generate Report:
      - Project Setup: project-setup.md
      - CLI Params: cli-params.md
    - Additional Resources:
        - Help with Tevico Community: help.md
        - Project Status & Support: project-status.md
  - Developer:
    - Get Started: developer/getting-started.md
    - Provider:
      - AWS:
        - Dev Setup: developer/provider/aws-dev-setup.md
    - Concepts:
      - Entities:
        - Check: developer/entities/check.md
        - Provider: developer/entities/provider.md
        - Profile: developer/entities/profile.md
        - Framework: developer/entities/framework.md
        - Channel: developer/entities/channel.md
      - Workflow: developer/concepts/workflow.md
      - File Structure: developer/concepts/file-structure.md

plugins:
  - search
  - open-in-new-tab

markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.tabbed:
      alternate_style: true
  - toc:
      permalink: true
      title: Page contents
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format